### ISSUE TITLE
[npc showing on playerlist]

### ISSUE THREAD

**Issue by khtpro** [FancyMcPlugins/FancyNpcs#132] opened 2024-07-03 18:21 UTC
npcs showing on Player list 

![Screenshot 2024-07-04 022019](https://github.com/FancyMcPlugins/FancyNpcs/assets/137651996/c31742aa-41fa-4a3f-8098-8e43ac69d81c)
![Screenshot 2024-07-04 022027](https://github.com/FancyMcPlugins/FancyNpcs/assets/137651996/3bf8d48d-47f4-4cf5-b438-8d08a4a1b1cb)

**Comment by ddsb520** [comment] 2024-07-10 02:11
yes
![image](https://github.com/FancyMcPlugins/FancyNpcs/assets/96320440/4f1a9140-3235-4111-bedf-4aa8a78b1c97)

**Comment by OliverSchlueter** [comment] 2024-07-12 20:53
Duplicate of #78 but might found a fix for it. I would move this converation to there

**Closed by OliverSchlueter** 2024-07-12 20:53 UTC
Labels: bug, duplicate
