### ISSUE TITLE
NPC gravity and general movement abilities

### ISSUE THREAD

**Issue by airoons** [FancyMcPlugins/FancyNpcs#75] opened 2024-01-25 09:18 UTC
I haven't worked as much with packet entities, so I am wondering whether it is feasible to add at least some basic "reactivity" to environment. 

It would be great to see at least gravity option for NPCs, as I assume anything hitbox, path or other actual movement related would be pain to implement, if possible at all.

Thanks

**Comment by OliverSchlueter** [comment] 2024-11-07 15:05
Duplicate of #77

**Closed by OliverSchlueter** 2024-11-07 15:05 UTC
Labels: feature request
