### ISSUE TITLE
Add support for modelEngine4

### ISSUE THREAD

**Issue by Z3r0xh** [FancyMcPlugins/FancyNpcs#189] opened 2024-10-30 14:05 UTC
It would be great if support could be added to meg4 to have custom NPC models.

**Comment by Grabsky** [comment] 2024-10-30 14:20
Duplicate of https://github.com/FancyMcPlugins/FancyNpcs/issues/165.

**Comment by OliverSchlueter** [comment] 2024-11-02 20:48
Duplicate

**Closed by OliverSchlueter** 2024-11-02 20:48 UTC
